### ISSUE TITLE
Milestone 1.0

### ISSUE THREAD

**Issue by cjlucas** [cjlucas/rtorrent-python#18]
This issue can be used as a forum for anything 1.0 related. Feel free to express any concerns/opinions here as I will be checking it regularly.
#### XMLRPC Connection support
- [ ] HTTP
- [ ] SCGI Port
- [ ] SCGI Socket
#### RPC Method Support
- [ ] rtorrent.RTorrent
- [ ] rtorrent.torrent.Torrent
- [ ] rtorrent.file.File
- [ ] rtorrent.peer.Peer
- [ ] rtorrent.tracker.Tracker
- [ ] Psuedo methods
#### Documentation
- [ ] rtorrent.RTorrent
- [ ] rtorrent.torrent.Torrent
- [ ] rtorrent.file.File
- [ ] rtorrent.peer.Peer
- [ ] rtorrent.tracker.Tracker

**Comment by RSully** [comment]
Nice to see a modern (re-)write. Is there an IRC room for this project?

**Comment by cjlucas** [comment]
I don't think this project is big enough to warrant an IRC channel. But feel free to email me with any questions.
